### ISSUE TITLE
repl prints ``` twice

### ISSUE THREAD

**Issue by Jan200101** [irdumbs/Dumb-Cogs#16]
as the title says repl prints ``` twice
![image](https://cloud.githubusercontent.com/assets/15076013/21511189/99f716a6-cc9d-11e6-815a-4bba2ae8f1e9.png)

**Comment by Chovin** [comment]
Thanks. Will fix soon.
REPL is in development rn

**Comment by Chovin** [comment]
d2bc3dd7969b068967c7aa4b5107488b588cd5fb should fix it.
update your bot 👍

**Comment by Jan200101** [comment]
Fixed 👍
