### ISSUE TITLE
repl doesnt pagify

### ISSUE THREAD

**Issue by Jan200101** [irdumbs/Dumb-Cogs#17]
as the title says repl doesnt pagify I would suggest making it like debug that it pagifys but stops and await a response when 2 full code boxes where send

**Comment by Chovin** [comment]
please post an example. it pagifies fine for me.

I like the suggestion to continue when prompted after 2 pages though.

**Comment by Jan200101** [comment]
dir(bot)

**Comment by Jan200101** [comment]
![image](https://cloud.githubusercontent.com/assets/15076013/21557211/3979c7c8-ce29-11e6-88d6-6e6ab9889e8f.png)

**Comment by Chovin** [comment]
That's most likely because you've set it to write to file.
`!help REPL`
p.s. give me a cookie

**Comment by Jan200101** [comment]
doing help repl gives me this
![image](https://cloud.githubusercontent.com/assets/15076013/21562629/b0a63a7e-ce7a-11e6-993e-fe075cc6de04.png)
so I guess that something to look for.

Good that help exists

p.s. I dont have cookies right now, need to buy some

**Comment by Chovin** [comment]
for peeps looking at this, `!help REPL` is what you want, not `!help repl`
