### ISSUE TITLE
Great cogs

### ISSUE THREAD

**Issue by ddday** [irdumbs/Dumb-Cogs#2]
Nice cogs but the lolz cog + the slots in the economy cog = no slot images
Maybe make the lolz cog ignore slots?

**Comment by irdumbs** [comment]
could make it ignore :emojis:

**Comment by ddday** [comment]
Sounds cool

**Comment by irdumbs** [comment]
[b915713](https://github.com/irdumbs/Dumb-Cogs/commit/b9157137de7126f6fc38c7de355ec941980632cc)

**Comment by irdumbs** [comment]
lolz also is available in PM now
for you creepy people that like talking to my bot in PM.
I see you >.>
