### ISSUE TITLE
Welcome Cog - Not working across Servers?

### ISSUE THREAD

**Issue by clovisd** [irdumbs/Dumb-Cogs#21]
Hey!

I was hoping to setup different welcome messages per server. However, the messages seem to be the same per server making it impossible to tailor the message to different servers.

Any possibility this could be added to future versions?

Thanks!

**Comment by Chovin** [comment]
please show screenshots of what you're trying.
seems to work fine over here.
Please go to the support channel to get faster help: https://discord.gg/GET4DVk

**Comment by clovisd** [comment]
I'm on the support channel right now.

**Comment by Chovin** [comment]
thank you for reporting this. it should be fixed now.
that's what you get for cutting corners in early development :P 

please confirm and close the issue if fixed

**Comment by clovisd** [comment]
It's working as intended now! Thanks! 👍
