### ISSUE TITLE
who is all a​lots?

### ISSUE THREAD

**Issue by ghost** [irdumbs/Dumb-Cogs#28]
"Invites all a​lots to your servers.

Also silently mentions them whenever someone says their name so that they pop into chat to see why people keep calling them."

wtf does that even mean? lol

**Comment by skeith** [comment]
http://hyperboleandahalf.blogspot.com/2010/04/alot-is-better-than-you-at-everything.html

**Comment by ghost** [comment]
huh

**Comment by Chovin** [comment]
> huh

heh

Try it n see. Check out the messy code if you're uncertain.
